version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_godb
    restart: always
    environment:
      TZ: ${TZ:-Asia/Tokyo}
      POSTGRES_DB: ${POSTGRES_DB:-dev}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - ${POSTGRES_PORT:-15432}:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d